# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push to the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: Build static web app bundle
        run: |
          yarn install
          yarn build
          
      - name: Prettier formatting check
        run: npx prettier --check src

      - name: Check that dependencies are compatible with MIT license
        run: npx license-checker --onlyAllow 'MIT;BSD;Apache-2.0;CC0-1.0;CC-BY-3.0;CC-BY-4.0;ISC;Hippocratic-2.1;MPL-2.0;ODC-By-1.0;WTFPL;Unlicense'

      - name: Create a new commit to gh-pages
        run: |
          git add --force build
          git -c user.name="GitHub Actions" -c user.email="actions@github.com" commit -m "Apply automatic changes" --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git subtree split --prefix build -b gh-pages
          git push --force origin gh-pages
